remove extraneous quotes

diff --git a/1/inpath b/1/inpath
--- a/1/inpath
+++ b/1/inpath
@@ -12,7 +12,7 @@ in_path()
    cmd=$1        ourpath=$2         result=1
    oldIFS=$IFS   IFS=":"
 
-   for directory in "$ourpath"
+   for directory in $ourpath
    do
      if [ -x $directory/$cmd ] ; then
        result=0      # if we're here, we found $cmd in $directory
@@ -38,15 +38,15 @@ in_path()
    fi
 }
 
-#if [ $# -ne 1 ] ; then
-#  echo "Usage: $0 command" >&2 ; exit 1
-#fi
+if [ $# -ne 1 ] ; then
+  echo "Usage: $0 command" >&2 ; exit 1
+fi
 
-#checkForCmdInPath "$1"
-#case $? in
-#  0 ) echo "$1 found in PATH"                   ;;
-#  1 ) echo "$1 not found or not executable"     ;;
-#  2 ) echo "$1 not found in PATH"               ;;
-#esac
+checkForCmdInPath "$1"
+case $? in
+  0 ) echo "$1 found in PATH"                   ;;
+  1 ) echo "$1 not found or not executable"     ;;
+  2 ) echo "$1 not found in PATH"               ;;
+esac
 
-#exit 0
+exit 0
