remove bad quotes

diff --git a/2/unrm b/2/unrm
--- a/2/unrm
+++ b/2/unrm
@@ -57,8 +57,8 @@ if [ $matches -gt 1 ] ; then
   echo ""
   echo -n "Which version of $1 do you want to restore ('0' to quit)? [1] : "
   read desired
-  if [ ! -z “$(echo $desired | sed 's/[[:digit:]]//g')” ] ; then
-    echo “$0: Restore canceled by user: invalid input.” >&2
+  if [ ! -z "$(echo $desired | sed 's/[[:digit:]]//g')" ] ; then
+    echo "$0: Restore canceled by user: invalid input." >&2
     exit 1
   fi
 
diff --git a/4/toolong b/4/toolong
--- a/4/toolong
+++ b/4/toolong
@@ -5,7 +5,7 @@
 width=72
 
 if [ ! -r "$1" ] ; then
-  echo “Cannot read file $1” >&2
+  echo "Cannot read file $1" >&2
   echo "Usage: $0 filename" >&2; exit 1
 fi
 
